buildscript {
    repositories {
        maven { url = "https://maven.minecraftforge.net/" }
    }
	dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:2.3.2"
	}
}

configurations {
    shade
    compile.extendsFrom shade
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven-publish'

repositories {
    maven {
        url "https://cursemaven.com"
    }
}

String umcVersion = mod_version
if (!"release".equalsIgnoreCase(System.getProperty("target"))) {
    try {
        umcVersion += "-" + 'git rev-parse --verify --short=7 HEAD'.execute().text.trim()
    } catch (Exception ex) {
        umcVersion += "-unknown"
    }
}

version = "1.12.2-forge-" + umcVersion
group = mod_group
archivesBaseName = mod_name

sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = "1.8"

minecraft {
    version = "${minecraft_version}-${forge_version}"
    runDir = "run"
    mappings = mappings_version
}

dependencies {
	shade "curse.maven:invtweaks-223094:2482482"

    shade group: 'at.yawk.lz4', name: 'lz4-java', version: '1.10.2'
    testCompile('junit:junit:4.13.1')
}

jar {
    configurations.shade.each { dep ->
        from(project.zipTree(dep)){
            exclude 'META-INF', 'META-INF/**'
        }
    }
    manifest {
        attributes 'FMLAT': "${mod_name}_at.cfg"
    }
}
jar.finalizedBy('reobfJar')

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "${minecraft_version}-${forge_version}"

    from(sourceSets.main.resources.srcDirs) {
        include "mcmod.info"
        expand "version": project.version, "mcversion": "${minecraft_version}-${forge_version}"
    }
        
    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude "mcmod.info"
    }
}

test {
    useJUnit()
    maxHeapSize = '1G'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifact sourceJar
            artifactId archivesBaseName
        }
    }
    repositories {
        maven {
            url "sftp://teamopenindustry.cc:22/var/www/html/maven/"
            credentials {
                username = "mavenci"
                password = System.getenv("MAVENCI_PASS")
            }
        }
    }
}

task showBuildInfo {
    doLast {
        System.out.println("Build Uploaded to Maven at: ")
        System.out.println("https://teamopenindustry.cc/maven/${mod_group.replace('.', '/')}/${mod_name}/${version}/${mod_name}-${version}.jar")
    }
}

publish.finalizedBy showBuildInfo