plugins {
    id 'java'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[7.0.30,8.0)'
    id 'net.minecraftforge.renamer' version '1.1.2'
    id 'com.gradleup.shadow' version "9.4.2"
}

configurations {
    shade
    implementation.extendsFrom shade
}

java {
    withSourcesJar()
}

repositories {
    maven {
        url = "https://cursemaven.com"
    }
}

String umcVersion = "1.3.0"
if (!"release".equalsIgnoreCase(System.getProperty("target"))) {
    try {
        umcVersion += "-${(providers.exec { commandLine("git", "rev-parse", "--verify", "--short=7", "HEAD") }.standardOutput.asText.get() as String).substring(0, 7)}"
    } catch (Exception ignored) {
        umcVersion += "-unknown"
    }
}
version = "1.14.4-forge-" + umcVersion
group = "cam72cam.universalmodcore" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
String archivesBaseName = "UniversalModCore"
base.archivesName = archivesBaseName

println("version: ${version}")

java.toolchain.languageVersion = JavaLanguageVersion.of(8)
println("Java: ${providers.systemProperty("java.version").get()}, " +
        "JVM: ${providers.systemProperty("java.vm.version").get()} (${providers.systemProperty("java.vendor").get()}), " +
        "Arch: ${providers.systemProperty("os.arch").get()}")

renamer.enableMixinRefmaps {
    config "mixins.feat.universalmodcore.json"
    config "mixins.fix.universalmodcore.json"
}

minecraft {
    mappings channel: "stable", version: "58-1.14.4"

    setAccessTransformer("META-INF/accesstransformer.cfg")

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')
            args "--mixin.config=mixins.feat.universalmodcore.json",
                    "--mixin.config=mixins.fix.universalmodcore.json"

            systemProperty "mixin.debug.verbose", "true"
            systemProperty "mixin.debug.export", "true"

            systemProperty "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
            systemProperty "forge.logging.console.level", "debug"
        }

        register("client")

        register("server") {
            args "--nogui"
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
    maven { url = "https://repo.spongepowered.org/maven" }
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:1.14.4-28.2.30")

    compileOnly ("org.lwjgl:lwjgl:3.2.2")
    compileOnly ("org.lwjgl:lwjgl-glfw:3.2.2")
    compileOnly ("org.lwjgl:lwjgl-opengl:3.2.2")

    annotationProcessor('org.spongepowered:mixin:0.8.5:processor')
    implementation renamer.dependency("curse.maven:mixinbootstrap-357178:3437402")
    annotationProcessor(shade('io.github.llamalad7:mixinextras-common:0.5.0'))

    testImplementation ('junit:junit:4.13.1')

    shade "at.yawk.lz4:lz4-java:1.10.2"
}

renamer.mappings.from minecraft.dependency.toSrgFile

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('processResources', ProcessResources) {
    // this will ensure that this task is redone when the versions change.
    inputs.property 'version', project.version
    inputs.property 'mcversion', "1.14.4"

    // replace stuff in mcmod.info, nothing else
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        // replace version and mcversion
        expand 'version':project.version, 'mcversion':"1.14.4"
    }

    // copy everything else except the mcmod.info
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }

    duplicatesStrategy = DuplicatesStrategy.WARN
}

jar {
    archiveClassifier = 'slim'
    manifest {
        attributes ([
                "Specification-Title": "universalmodcore",
                "Specification-Vendor": "",
                "Specification-Version": "1", // We are version 1 of ourselves
                "Implementation-Title": project.name,
                "Implementation-Version": umcVersion,
                "Implementation-Vendor" :"",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

renamer.classes(tasks.named('jar', Jar)) {
    archiveClassifier = 'slim'
    // We need to use the generated mappings, which includes things generated by the annotation processor
    mappings renamer.mixin.generatedMappings
    output = input.map { inputFile ->
        layout.buildDirectory.file("libs/${inputFile.asFile.name}").get()
    }
}

tasks.named("shadowJar") {
    archiveClassifier = ''
    configurations = project.configurations.named('shade').map { [it] }
    relocate 'com.llamalad7', "${project.group}.shade.com.llamalad7"
    relocate 'net.jpountz', "${project.group}.shade.net.jpountz"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
}

renamer.classes(tasks.named('shadowJar', Jar)) {
    archiveClassifier = ''
    // We need to use the generated mappings, which includes things generated by the annotation processor
    mappings renamer.mixin.generatedMappings
    output = input.map { inputFile ->
        layout.buildDirectory.file("libs/${inputFile.asFile.name}").get()
    }
}



assemble.dependsOn shadowJar

test {
    useJUnit()
    maxHeapSize = '1G'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact renameShadowJar
            artifact sourcesJar
            artifactId = archivesBaseName
        }
    }
    repositories {
        maven {
            url = "sftp://teamopenindustry.cc:22/var/www/html/maven/"
            credentials {
                username = "mavenci"
                password = System.getenv("MAVENCI_PASS")
            }
        }
    }
}

tasks.register('showBuildInfo') {
    doLast {
        System.out.println("Build Uploaded to Maven at: ")
        System.out.println("https://teamopenindustry.cc/maven/cam72cam/universalmodcore/UniversalModCore/${version}/UniversalModCore-${version}.jar")
    }
}

publish.finalizedBy showBuildInfo

// IntelliJ no longer downloads javadocs and sources by default, this tells Gradle to force IntelliJ to do it.
idea.module { downloadJavadoc = downloadSources = true }

eclipse {
    // Eclipse no longer downloads javadocs and sources by default, this tells Gradle to force Eclipse to do it.
    classpath { downloadJavadoc = downloadSources = true }

    // NOTE: ForgeGradle 7 does not yet support Eclipse run configurations
    // Run everytime eclipse builds the code
    //autoBuildTasks genEclipseRuns
    // Run when importing the project
    //synchronizationTasks 'genEclipseRuns'
}
