# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
# Forge why you so broken???
org.gradle.daemon=false

minecraft_version=1.12.2
forge_version=14.23.5.2847
mappings_version=stable_39

mod_group=cam72cam.universalmodcore
mod_name=UniversalModCore
mod_version=1.3.0