modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TeamOpenIndustry/UniversalModCore/issues"
license="LGPL"

[[mods]]
modId="universalmodcore"
version="1.2.2"
displayName="Universal Mod Core"
displayURL="https://github.com/TeamOpenIndustry/UniversalModCore"
authors="cam72cam"
description='''
Universal Mod API (Minecraft version agnostic)
'''

[[mixins]]
config="mixins.feat.universalmodcore.json"
[[mixins]]
config="mixins.fix.universalmodcore.json"

[[dependencies.universalmodcore]]
    modId="neoforge"
    type='required'
    versionRange="[20.4.250,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.universalmodcore]]
    modId="minecraft"
    type='required'
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"
