modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/TeamOpenIndustry/UniversalModCore/issues"
license="LGPL"

[[mods]]
modId="universalmodcore"
version="1.2.4"
displayName="Universal Mod Core"
displayURL="https://github.com/TeamOpenIndustry/UniversalModCore"
authors="cam72cam"
description='''
Universal Mod API (Minecraft version agnostic)
'''

[[mixins]]
config="mixins.feat.universalmodcore.json"
[[mixins]]
config="mixins.fix.universalmodcore.json"

[modproperties.universalmodcore."yumi:entrypoints"]
"lambdynlights:initializer" = "cam72cam.mod.render.Light$UMCDynLightInitializer"

[[dependencies.universalmodcore]]
    modId="neoforge"
    type='required'
    versionRange="[21.1.216,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.universalmodcore]]
    modId="minecraft"
    type='required'
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"
