//BUILDSCRIPT//
plugins {
    id 'java'
    //A customized fork for better support on Cleanroom
    id 'xyz.wagyourtail.unimined' version "1.4.18-kappa"
    id 'com.gradleup.shadow' version "8.3.10"
    id "maven-publish"
    id 'xyz.wagyourtail.jvmdowngrader' version '1.3.6'
}
configurations {
    umcShade
    modImplementation.extendsFrom umcShade
}
unimined.useGlobalCache = false

//PLUGINS//

//MINECRAFT//
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

jvmdg {
    quiet = false
    multiReleaseOriginal = true
    //Downgrade to Java8 for MinecraftForge, preserve Java25 for Cleanroom
    multiReleaseVersions = [JavaVersion.VERSION_1_8, JavaVersion.VERSION_25].toSet()
}

unimined.minecraft {
    version "1.12.2"

    mappings {
        searge()
        mcp("stable", "39-1.12")
    }

    cleanroom {
        loader("0.5.12-alpha")
    }

    defaultRemapJar = true
}

//DEPENDENCIES//
#UMC_REPO#

dependencies {
    compileOnly "com.cleanroommc:lwjglx:1.0.0"
    modImplementation #UMC_DEPENDENCY#
}

//JAR//
jar {
    enabled = false
}

shadowJar {
    configurations = [project.configurations.umcShade]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
    archiveClassifier = 'shadow'
//    finalizedBy 'reobfShadowJar'
}

shadeDowngradedApi {
    inputFile = shadowJar.archiveFile
}

remapJar {
    inputFile = tasks.shadeDowngradedApi.archiveFile
    dependsOn(tasks.named("shadowJar"))
    archiveClassifier = ''
}

tasks.named("assemble") {
    dependsOn(tasks.named("remapJar"))
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property "version", project.version
    inputs.property "mcversion", "#MINECRAFT#"
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':"#MINECRAFT#"
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
