//BUILDSCRIPT//
plugins {
    id 'java'
    //A customized fork for better support on Cleanroom
    id 'xyz.wagyourtail.unimined' version "1.4.18-kappa"
    id 'com.gradleup.shadow' version "9.4.1"
    id "maven-publish"
    id 'xyz.wagyourtail.jvmdowngrader' version '2.0.1'
}
configurations {
    umcShade
    modImplementation.extendsFrom umcShade
}

//PLUGINS//

//MINECRAFT//
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }

    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
    options.encoding = 'UTF-8'
}

jvmdg {
    quiet = false
    downgradeTo = JavaVersion.VERSION_1_8
    //Will introduce some untraceable bugs, investigate later
    //multiReleaseOriginal = true
    shadeInlining = false
    dg(configurations.umcShade, false)
}

unimined.minecraft {
    version "1.12.2"

    mappings {
        searge()
        mcp("stable", "39-1.12")
    }

    cleanroom {
        loader("0.5.12-alpha")
    }

    defaultRemapJar = true
}

//DEPENDENCIES//
#UMC_REPO#

repositories {
    maven { url = 'https://maven.cleanroommc.com' }
}

dependencies {
    compileOnly "com.cleanroommc:lwjglx:1.0.0"
    modImplementation ('zone.rong:mixinbooter:10.7') { transitive = false }
    modImplementation #UMC_DEPENDENCY#
}

//JAR//
jar {
    enabled = false
}

shadowJar {
    configurations = [project.configurations.umcShade]
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
    archiveClassifier = 'shadow'
}

remapJar {
    inputFile = tasks.shadeDowngradedApi.archiveFile
    dependsOn(tasks.named("shadowJar"))
    archiveClassifier = ''
}

tasks.named("assemble") {
    dependsOn(tasks.named("remapJar"))
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    inputs.property "version", project.version
    inputs.property "mcversion", "#MINECRAFT#"
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':"#MINECRAFT#"
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
