//BUILDSCRIPT//
buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven { url = "https://maven.minecraftforge.net/" }
    }
	dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
        classpath 'com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin:2.0.4'
	}
}

configurations {
    umcShadow
    compile.extendsFrom umcShadow

    umcImplementation
    compile.extendsFrom umcImplementation

    umcCompileOnly
    provided.extendsFrom umcCompileOnly

    umcRuntimeOnly
    runtime.extendsFrom umcRuntimeOnly
}

//PLUGINS//
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'com.github.johnrengelman.shadow'


//MINECRAFT//
sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "stable_39"
}

//DEPENDENCIES//
#UMC_REPO#

dependencies {
    umcRuntimeOnly "net.minecrell:terminalconsoleappender:1.3.0"
    umcImplementation #UMC_DEPENDENCY#
}

//JAR//
shadowJar {
    classifier = ''
    configurations = [project.configurations.umcShadow]
    #RELOCATION#
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    mergeServiceFiles()
    finalizedBy 'reobfShadowJar'
}

reobf {
    shadowJar {}
}

assemble.dependsOn shadowJar

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}
