package cam72cam.mod;

import net.minecraftforge.fml.common.FMLModContainer;
import net.minecraftforge.fml.common.MetadataCollection;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.discovery.ModCandidate;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;

import java.util.Map;

/**
 * Wrapper to register UMC mods in <code>ModCore</code>
 */
public class UMCModContainer extends FMLModContainer {
    ModCandidate candidate;
    Map<String, Object> modDescriptor;

    public UMCModContainer(String className, ModCandidate candidate, Map<String, Object> modDescriptor) {
        super(className, candidate, modDescriptor);
        this.candidate = candidate;
        this.modDescriptor = modDescriptor;
    }

    @Override
    public void constructMod(FMLConstructionEvent event) {
        super.constructMod(event);
        ModCore.register((ModCore.Mod) getMod());
    }

    @Override
    public void bindMetadata(MetadataCollection mc) {
        super.bindMetadata(mc);
        //Then we'll override some of those
        //TODO
//        InputStream umcJson = new ZipInputStream(candidate.getModContainer())
        ModMetadata modMetadata = this.getMetadata();

        modMetadata.modId = (String) modDescriptor.get("modid");
        modMetadata.name = (String) modDescriptor.get("name");
        modMetadata.version = (String) modDescriptor.get("version");
        modMetadata.autogenerated = false;
    }
}
