package cam72cam.mod;

import net.minecraftforge.fml.common.FMLContainer;
import net.minecraftforge.fml.common.FMLModContainer;
import net.minecraftforge.fml.common.MetadataCollection;
import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.discovery.ModCandidate;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;

import java.io.InputStream;
import java.lang.reflect.Field;
import java.util.Map;
import java.util.zip.ZipInputStream;

/**
 * Wrapper to register UMC mods in <code>ModCore</code>
 */
public class UMCModContainer extends FMLModContainer {
    ModCandidate candidate;

    public UMCModContainer(String className, ModCandidate candidate, Map<String, Object> modDescriptor) {
        super(className, candidate, modDescriptor);
        this.candidate = candidate;
    }

    @Override
    public void constructMod(FMLConstructionEvent event) {
        super.constructMod(event);
        ModCore.register((ModCore.Mod) getMod());
    }

    @Override
    public void bindMetadata(MetadataCollection mc) {
        super.bindMetadata(mc);
        //Then we'll override some of those
        //TODO
//        InputStream umcJson = new ZipInputStream(candidate.getModContainer())
        try {

            Field field = FMLModContainer.class.getDeclaredField("descriptor");
            field.setAccessible(true);
            Map<String, Object> descriptor = (Map<String, Object>) field.get(this);
            ModMetadata modMetadata = mc.getMetadataForId(getModId(), descriptor);

            modMetadata.modId = (String) descriptor.get("modid");
            modMetadata.name = (String) descriptor.get("name");
            modMetadata.version = (String) descriptor.get("version");
            modMetadata.autogenerated = false;

            field = FMLModContainer.class.getDeclaredField("modMetadata");
            field.setAccessible(true);
            field.set(this, modMetadata);
        } catch (NoSuchFieldException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }
}
