package cam72cam.mod.loader;

import cam72cam.mod.ModCore;
import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;
import net.minecraft.client.resources.FolderResourcePack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.client.FMLFolderResourcePack;
import net.minecraftforge.fml.common.*;
import net.minecraftforge.fml.common.discovery.ModCandidate;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.versioning.ArtifactVersion;
import net.minecraftforge.fml.common.versioning.InvalidVersionSpecificationException;
import net.minecraftforge.fml.common.versioning.VersionRange;
import org.apache.logging.log4j.message.FormattedMessage;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.*;

public class UMCModContainer extends DummyModContainer {
    ModCandidate candidate;
    File source;
    ModCore.Mod instance;

    String modId;
    String displayName;
    String mainClass;
    String version;
    List<String> authors;
    List<String> description;
    URL modURL;
    String license;
    Map<String, ArtifactVersion> dependencies;
    File resourcesRoot;

    ModMetadata meta;

    private EventBus eventBus;

    @Override
    public String getModId() {
        return modId;
    }

    @Override
    public String getName() {
        return displayName;
    }

    @Override
    public String getVersion() {
        return version;
    }

    @Override
    public File getSource() {
        return source;
    }

    @Override
    public void setEnabledState(boolean enabled) {
        //NO-OP as UMC mods cannot be disabled
    }

    @Override
    public List<ArtifactVersion> getDependencies() {
        return new ArrayList<>(dependencies.values());
    }

    @Override
    public void bindMetadata(MetadataCollection mc) {
        meta = new ModMetadata();
        meta.modId = modId;
        meta.name = displayName;
        meta.version = version;
        meta.autogenerated = false;
        meta.authorList = authors;
        meta.url = modURL == null ? "" : modURL.toString();
        meta.description = String.join("\n", description);
        meta.dependencies = new ArrayList<>(dependencies.values());
    }

    @Override
    public ModMetadata getMetadata() {
        return meta;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller) {
        FMLLog.log.debug("Enabling mod {}", getModId());
        this.eventBus = bus;
        eventBus.register(this);
        return true;
    }

    @Override
    public boolean matches(Object mod) {
        return mod instanceof ModCore.Mod && mod == instance;
    }


    @Subscribe
    public void constructMod(FMLConstructionEvent event) {
        ModClassLoader modClassLoader = event.getModClassLoader();
        try
        {
            modClassLoader.addFile(source);
        }
        catch (MalformedURLException e)
        {
            FormattedMessage message = new FormattedMessage("{} Failed to add file to classloader: {}", getModId(), source);
            throw new LoaderException(message.getFormattedMessage(), e);
        }
        modClassLoader.clearNegativeCacheFor(candidate.getClassList());

        //Only place I could think to add this...
        MinecraftForge.preloadCrashClasses(event.getASMHarvestedData(), getModId(), candidate.getClassList());

        Class<?> clazz;
        try
        {
            clazz = Class.forName(mainClass, true, modClassLoader);
            instance = (ModCore.Mod) clazz.newInstance();
            ModCore.register(instance);
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException e)
        {
            FormattedMessage message = new FormattedMessage("{} Failed load class: {}", getModId(), mainClass);
            throw new LoaderException(message.getFormattedMessage(), e);
        }
    }

    @Override
    public Class<?> getCustomResourcePackClass()
    {
        return resourcesRoot != null ? DevFolderPack.class : null;
    }

    @Override
    public Object getMod() {
        return instance;
    }

    @Override
    public String getDisplayVersion() {
        return version;
    }

    @Override
    public VersionRange acceptableMinecraftVersionRange() {
        try {
            return VersionRange.createFromVersionSpec("[1.7.10, )");
        } catch (InvalidVersionSpecificationException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public boolean shouldLoadInEnvironment() {
        //TODO Side only
        return true;
    }

    @Override
    public URL getUpdateUrl() {
        return modURL;
    }

    @Override
    public int getClassVersion() {
        return 52; //Compatible with Java8
    }

    @Override
    public String toString() {
        return String.format("UMC Mod %s:%s", getName(), getVersion());
    }

    public static class DevFolderPack extends FolderResourcePack implements FMLContainerHolder {
        private final ModContainer container;

        public DevFolderPack(ModContainer container)
        {
            super(container instanceof UMCModContainer ? ((UMCModContainer) container).resourcesRoot : container.getSource());
            this.container = container;
        }

        @Override
        protected boolean hasResourceName(String name)
        {
            return super.hasResourceName(name);
        }
        @Override
        public String getPackName()
        {
            return "DevFolderPack:"+container.getName();
        }
        @Override
        protected InputStream getInputStreamByName(String resourceName) throws IOException
        {
            try
            {
                return super.getInputStreamByName(resourceName);
            }
            catch (IOException exception)
            {
                if ("pack.mcmeta".equals(resourceName)) {
                    //Generate a dummy pack.mcmeta
                    return new ByteArrayInputStream(("{\n" +
                            " \"pack\": {\n"+
                            "   \"description\": \"UMC generated pack for "+container.getName()+"\",\n"+
                            "   \"pack_format\": 2\n"+
                            "}\n" +
                            "}").getBytes(StandardCharsets.UTF_8));
                } else {
                    throw exception;
                }
            }
        }

        @Override
        public BufferedImage getPackImage() throws IOException
        {
            return ImageIO.read(getInputStreamByName(container.getMetadata().logoFile));
        }

        @Override
        public ModContainer getFMLContainer()
        {
            return container;
        }
    }
}
