modLoader="javafml"
loaderVersion="[2,)"
license="TODO"

[[mods]]
modId="#ID#"
version="${file.jarVersion}"
displayName="#NAME#"

[[dependencies.#ID#]]
    modId="neoforge"
    type='required'
    versionRange="[21.4.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.#ID#]]
    modId="minecraft"
    type='required'
    versionRange="[1.21.4]"
    ordering="NONE"
    side="BOTH"

#FORGE_TOML_DEPENDENCIES#
