name: Universal Mod Core CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v4
              with:
                java-version: '17'
                distribution: 'temurin'
            - run: |
                ref=`echo ${github_ref} | sed -e 's,refs/heads/,,' | tr '/' '-'`
                echo $ref
                echo "::set-env name=ref::$ref"
              env:
                github_ref: ${{ github.ref }}
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            - name: keyscan
              run: mkdir -p ~/.ssh/ && ssh-keyscan -t rsa teamopenindustry.cc >> ~/.ssh/known_hosts
            - name: Gradle publish
              env:
                MAVENCI_PASS: ${{ secrets.MAVENCI_PASS }}
              run: ./gradlew publish
            - uses: actions/upload-artifact@v4
              with:
                name: UniversalModCore-${{ env.ref }}
                path: build/libs/UniversalModCore-*.jar
